resources:
  - name: repo
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78//nativesteps   
      branches:
        include: master

pipelines: 
  - name: dockerPipe
    steps:
      - name: buildStep
        type: DockerBuild
        configuration:
          #inherits from bash
          # for docker:
#           dockerFileLocation: <string> # optional, defaults to .
#           dockerFileName: <string>     # optional, defaults to Dockerfile
          dockerImageName: dev.jfrog-pipelines.com/rak_docker/img   
          dockerImageTag:  ${run_number}    
#           dockerOptions: <string>      # optional
          inputResources:
#             - artifactoryFileSpec      # optional
#             - someGitRepoResource      # required
              - name: repo   # optional if base image is private

